/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// registers
#define RCC_Base    0x40021000
#define PortA_Base  0x40010800

#define Set_bit(reg,bit)     (reg|=(1<<bit))
#define Clear_bit(reg,bit)   (reg&=~(1<<bit))

#define RCC_APB2ENR  *((volatile int*)(RCC_Base+0x18))
#define GPIOA_CRH    *((volatile int*)(PortA_Base+0x04))
#define GPIOA_ODR    *((volatile int*)(PortA_Base+0x0c))


int main(void)
{
	// write on registers
	RCC_APB2ENR |=1<<2; // set the
	GPIOA_CRH&=0xff0fffff; // clear bits from bit 20 to 24
	GPIOA_CRH|=0x00200000;// set 2 on bits from bit 20 to 24


    while(1){

    	Set_bit(GPIOA_ODR,13); // set bit 13
    	for(int i=0;i<5000;i++); // delay 5 ms
    	Clear_bit(GPIOA_ODR,13); // clear bit 13
    	for(int i=0;i<5000;i++); // delay 5 ms

    }
    return 0;
}
